#!/bin/bash
# Linux Basic Commands Reference Script

echo "============================"
echo " Basic File and Directory Commands "
echo "============================"
echo "ls - Lists directory contents"
echo "cd - Changes current directory"
echo "pwd - Prints current working directory"
echo "mkdir - Creates a new directory"
echo "rm - Removes files or directories"
echo "touch - Creates or updates a file timestamp"
echo "cp - Copies files or directories"
echo "mv - Moves or renames files or directories"
echo "ln - Creates hard or soft links"

echo ""
echo "============================"
echo " File Viewing and Manipulation Commands "
echo "============================"
echo "cat - Displays file content"
echo "head - Shows first few lines of a file"
echo "less - Scrolls through a file"
echo "wc - Counts lines, words, and characters"
echo "cut - Extracts sections from lines"
echo "sort - Sorts lines in a file"
echo "tee - Displays and writes output to file"
echo "diff - Compares two files"
echo "vi - Opens a text editor"

echo ""
echo "============================"
echo " Process Management and System Info "
echo "============================"
echo "ssh - Secure remote login"
echo "df - Displays disk space usage"
echo "du - Shows directory size"
echo "ps - Lists running processes"
echo "top - Displays active processes dynamically"
echo "kill - Terminates a process by PID"
echo "nohup - Runs a command immune to hangups"
echo "vmstat - Displays system performance stats"
echo "free - Shows memory usage"

echo ""
echo "============================"
echo " Hard Link vs Soft Link Concepts "
echo "============================"
echo "Hard Link: Another name for the same file data; data persists until all links are deleted."
echo "Soft Link: A symbolic shortcut pointing to another file; breaks if the target is removed."

echo ""
echo "============================"
echo " Example Usage "
echo "============================"
echo "mkdir test_dir"
echo "cd test_dir"
echo "touch file1.txt"
echo "echo 'Hello Linux' > file1.txt"
echo "cat file1.txt"
echo "sort file1.txt"
echo "cp file1.txt copy.txt"
echo "diff file1.txt copy.txt"
echo "vi file1.txt"
